"""rename department

Revision ID: 744e100def32
Revises: ce14e414c37b
Create Date: 2025-04-03 09:46:08.975041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744e100def32'
down_revision = 'ce14e414c37b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
